name: VEZA
description: A Video Calling App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agora_rtc_engine: ^4.0.2
  permission_handler: ^8.1.1
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^2.2.2
  random_string: ^2.1.0
  clipboard: ^0.1.3
  image_picker: ^0.8.1+1
  firebase_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/ronaldo.jpg
    - images/Meeting.png
    - images/background.jpg
    - images/Veza.png
